services:
  redlib:
    # image: quay.io/redlib/redlib:latest
    # image: quay.io/redlib/redlib:latest-arm # uncomment if you use arm64
    # using my local image
    image: redlib:latest
    # build : .
    # image: quay.io/redlib/redlib:latest-armv7 # uncomment if you use armv7
    restart: always
    container_name: "redlib"
    ports:
      - '127.0.0.1:8091:8080' # Specify `127.0.0.1:8080:8080` instead if using a reverse proxy
    user: nobody
    read_only: true
    security_opt:
      - no-new-privileges:true
      # - seccomp=seccomp-redlib.json
    cap_drop:
      - ALL
    env_file: .env
    networks:
      - redlib
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "--tries=1", "http://localhost:8080/settings"]
      interval: 5m
      timeout: 3s
  
  anubis:
    image: ghcr.io/techarohq/anubis:latest
    container_name: anubis
    environment:
      BIND: ":8923"
      DIFFICULTY: "4"
      METRICS_BIND: ":9090"
      SERVE_ROBOTS_TXT: "true"
      TARGET: "http://redlib:8080"
      POLICY_FNAME: "/data/cfg/botPolicy.yaml"
      OG_PASSTHROUGH: "true"
      OG_EXPIRY_TIME: "24h"
      COOKIE_DYNAMIC_DOMAIN: true
      # required when sitting behind Cloudflare
      JWT_RESTRICTINO_HEADER: CF-Connecting-IP
    healthcheck:
      test: ["CMD", "anubis", "--healthcheck"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 500ms
    ports:
      - 8082:8923
    volumes:
      - "../anubis/botpolicy:/data/cfg:ro"
    restart: always
    networks:
      - redlib
    depends_on:
      - redlib

networks:
  redlib:
